export type ItemId = string;
export type MachineId = string;
export type RecipeId = string;

export interface Item {
  id: ItemId;
  name: string;
  imageUrl?: string;
}

export interface ResourceInput {
  itemId: ItemId;
  rate: number; // per minute
}

export interface Recipe {
  id: RecipeId;
  outputItemId: ItemId;
  outputRate: number; // per minute
  inputs: ResourceInput[];
  machineId: MachineId;
}

export interface Machine {
  id: MachineId;
  name: string;
  powerUsage: number; // MW
  imageUrl: string;
}

// Initial Data
export const items: Record<ItemId, Item> = {
  limestone: { id: "limestone", name: "Limestone", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Limestone.png" },
  iron_ore: { id: "iron_ore", name: "Iron Ore", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iron_Ore.png" },
  copper_ore: { id: "copper_ore", name: "Copper Ore", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Copper_Ore.png" },
  caterium_ore: { id: "caterium_ore", name: "Caterium Ore", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Caterium_Ore.png" },
  coal: { id: "coal", name: "Coal", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Coal.png" },
  raw_quartz: { id: "raw_quartz", name: "Raw Quartz", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Raw_Quartz.png" },
  sulfur: { id: "sulfur", name: "Sulfur", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Sulfur.png" },
  bauxite: { id: "bauxite", name: "Bauxite", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Bauxite.png" },
  sam: { id: "sam", name: "SAM", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/SAM.png" },
  uranium: { id: "uranium", name: "Uranium", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Uranium.png" },
  iron_ingot: { id: "iron_ingot", name: "Iron Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iron_Ingot.png" },
  copper_ingot: { id: "copper_ingot", name: "Copper Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Copper_Ingot.png" },
  caterium_ingot: { id: "caterium_ingot", name: "Caterium Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Caterium_Ingot.png" },
  steel_ingot: { id: "steel_ingot", name: "Steel Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Steel_Ingot.png" },
  aluminum_ingot: { id: "aluminum_ingot", name: "Aluminum Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Aluminum_Ingot.png" },
  ficsite_ingot: { id: "ficsite_ingot", name: "Ficsite Ingot", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ficsite_Ingot.png" },
  concrete: { id: "concrete", name: "Concrete", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Concrete.png" },
  quartz_crystal: { id: "quartz_crystal", name: "Quartz Crystal", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Quartz_Crystal.png" },
  silica: { id: "silica", name: "Silica", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Silica.png" },
  copper_powder: { id: "copper_powder", name: "Copper Powder", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Copper_Powder.png" },
  polymer_resin: { id: "polymer_resin", name: "Polymer Resin", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Polymer_Resin.png" },
  petroleum_coke: { id: "petroleum_coke", name: "Petroleum Coke", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Petroleum_Coke.png" },
  aluminum_scrap: { id: "aluminum_scrap", name: "Aluminum Scrap", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Aluminum_Scrap.png" },
  alien_protein: { id: "alien_protein", name: "Alien Protein", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Alien_Protein.png" },
  alien_dna_capsule: { id: "alien_dna_capsule", name: "Alien DNA Capsule", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Alien_DNA_Capsule.png" },
  water: { id: "water", name: "Water", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Water.png" },
  crude_oil: { id: "crude_oil", name: "Crude Oil", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Crude_Oil.png" },
  heavy_oil_residue: { id: "heavy_oil_residue", name: "Heavy Oil Residue", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Heavy_Oil_Residue.png" },
  fuel: { id: "fuel", name: "Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Fuel.png" },
  liquid_biofuel: { id: "liquid_biofuel", name: "Liquid Biofuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Liquid_Biofuel.png" },
  turbofuel: { id: "turbofuel", name: "Turbofuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Turbofuel.png" },
  alumina_solution: { id: "alumina_solution", name: "Alumina Solution", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Alumina_Solution.png" },
  sulfuric_acid: { id: "sulfuric_acid", name: "Sulfuric Acid", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Sulfuric_Acid.png" },
  nitric_acid: { id: "nitric_acid", name: "Nitric Acid", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Nitric_Acid.png" },
  dissolved_silica: { id: "dissolved_silica", name: "Dissolved Silica", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Dissolved_Silica.png" },
  nitrogen_gas: { id: "nitrogen_gas", name: "Nitrogen Gas", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Nitrogen_Gas.png" },
  rocket_fuel: { id: "rocket_fuel", name: "Rocket Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Rocket_Fuel.png" },
  ionized_fuel: { id: "ionized_fuel", name: "Ionized Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ionized_Fuel.png" },
  dark_matter_residue: { id: "dark_matter_residue", name: "Dark Matter Residue", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Dark_Matter_Residue.png" },
  excited_photonic_matter: { id: "excited_photonic_matter", name: "Excited Photonic Matter", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Excited_Photonic_Matter.png" },
  iron_rod: { id: "iron_rod", name: "Iron Rod", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iron_Rod.png" },
  screw: { id: "screw", name: "Screw", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Screw.png" },
  iron_plate: { id: "iron_plate", name: "Iron Plate", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iron_Plate.png" },
  reinforced_iron_plate: { id: "reinforced_iron_plate", name: "Reinforced Iron Plate", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Reinforced_Iron_Plate.png" },
  copper_sheet: { id: "copper_sheet", name: "Copper Sheet", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Copper_Sheet.png" },
  alclad_aluminum_sheet: { id: "alclad_aluminum_sheet", name: "Alclad Aluminum Sheet", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Alclad_Aluminum_Sheet.png" },
  aluminum_casing: { id: "aluminum_casing", name: "Aluminum Casing", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Aluminum_Casing.png" },
  steel_pipe: { id: "steel_pipe", name: "Steel Pipe", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Steel_Pipe.png" },
  steel_beam: { id: "steel_beam", name: "Steel Beam", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Steel_Beam.png" },
  encased_industrial_beam: { id: "encased_industrial_beam", name: "Encased Industrial Beam", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Encased_Industrial_Beam.png" },
  modular_frame: { id: "modular_frame", name: "Modular Frame", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Modular_Frame.png" },
  heavy_modular_frame: { id: "heavy_modular_frame", name: "Heavy Modular Frame", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Heavy_Modular_Frame.png" },
  fused_modular_frame: { id: "fused_modular_frame", name: "Fused Modular Frame", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Fused_Modular_Frame.png" },
  ficsite_trigon: { id: "ficsite_trigon", name: "Ficsite Trigon", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ficsite_Trigon.png" },
  fabric: { id: "fabric", name: "Fabric", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Fabric.png" },
  plastic: { id: "plastic", name: "Plastic", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Plastic.png" },
  rubber: { id: "rubber", name: "Rubber", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Rubber.png" },
  rotor: { id: "rotor", name: "Rotor", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Rotor.png" },
  stator: { id: "stator", name: "Stator", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Stator.png" },
  battery: { id: "battery", name: "Battery", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Battery.png" },
  motor: { id: "motor", name: "Motor", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Motor.png" },
  heat_sink: { id: "heat_sink", name: "Heat Sink", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Heat_Sink.png" },
  cooling_system: { id: "cooling_system", name: "Cooling System", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Cooling_System.png" },
  turbo_motor: { id: "turbo_motor", name: "Turbo Motor", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Turbo_Motor.png" },
  wire: { id: "wire", name: "Wire", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Wire.png" },
  cable: { id: "cable", name: "Cable", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Cable.png" },
  quickwire: { id: "quickwire", name: "Quickwire", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Quickwire.png" },
  circuit_board: { id: "circuit_board", name: "Circuit Board", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Circuit_Board.png" },
  ai_limiter: { id: "ai_limiter", name: "AI Limiter", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/AI_Limiter.png" },
  high_speed_connector: { id: "high_speed_connector", name: "High-Speed Connector", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/High-Speed_Connector.png" },
  reanimated_sam: { id: "reanimated_sam", name: "Reanimated SAM", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Reanimated_SAM.png" },
  sam_fluctuator: { id: "sam_fluctuator", name: "SAM Fluctuator", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/SAM_Fluctuator.png" },
  computer: { id: "computer", name: "Computer", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Computer.png" },
  supercomputer: { id: "supercomputer", name: "Supercomputer", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Supercomputer.png" },
  radio_control_unit: { id: "radio_control_unit", name: "Radio Control Unit", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Radio_Control_Unit.png" },
  crystal_oscillator: { id: "crystal_oscillator", name: "Crystal Oscillator", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Crystal_Oscillator.png" },
  superposition_oscillator: { id: "superposition_oscillator", name: "Superposition Oscillator", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Superposition_Oscillator.png" },
  diamonds: { id: "diamonds", name: "Diamonds", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Diamonds.png" },
  time_crystal: { id: "time_crystal", name: "Time Crystal", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Time_Crystal.png" },
  dark_matter_crystal: { id: "dark_matter_crystal", name: "Dark Matter Crystal", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Dark_Matter_Crystal.png" },
  singularity_cell: { id: "singularity_cell", name: "Singularity Cell", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Singularity_Cell.png" },
  neural_quantum_processor: { id: "neural_quantum_processor", name: "Neural-Quantum Processor", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Neural-Quantum_Processor.png" },
  alien_power_matrix: { id: "alien_power_matrix", name: "Alien Power Matrix", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Alien_Power_Matrix.png" },
  empty_canister: { id: "empty_canister", name: "Empty Canister", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Empty_Canister.png" },
  empty_fluid_tank: { id: "empty_fluid_tank", name: "Empty Fluid Tank", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Empty_Fluid_Tank.png" },
  pressure_conversion_cube: { id: "pressure_conversion_cube", name: "Pressure Conversion Cube", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Pressure_Conversion_Cube.png" },
  packaged_water: { id: "packaged_water", name: "Packaged Water", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Water.png" },
  packaged_alumina_solution: { id: "packaged_alumina_solution", name: "Packaged Alumina Solution", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Alumina_Solution.png" },
  packaged_sulfuric_acid: { id: "packaged_sulfuric_acid", name: "Packaged Sulfuric Acid", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Sulfuric_Acid.png" },
  packaged_nitric_acid: { id: "packaged_nitric_acid", name: "Packaged Nitric Acid", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Nitric_Acid.png" },
  packaged_nitrogen_gas: { id: "packaged_nitrogen_gas", name: "Packaged Nitrogen Gas", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Nitrogen_Gas.png" },
  leaves: { id: "leaves", name: "Leaves", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Leaves.png" },
  mycelia: { id: "mycelia", name: "Mycelia", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Mycelia.png" },
  flower_petals: { id: "flower_petals", name: "Flower Petals", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Flower_Petals.png" },
  wood: { id: "wood", name: "Wood", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Wood.png" },
  biomass: { id: "biomass", name: "Biomass", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Biomass.png" },
  compacted_coal: { id: "compacted_coal", name: "Compacted Coal", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Compacted_Coal.png" },
  packaged_oil: { id: "packaged_oil", name: "Packaged Oil", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Oil.png" },
  packaged_heavy_oil_residue: { id: "packaged_heavy_oil_residue", name: "Packaged Heavy Oil Residue", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Heavy_Oil_Residue.png" },
  solid_biofuel: { id: "solid_biofuel", name: "Solid Biofuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Solid_Biofuel.png" },
  packaged_fuel: { id: "packaged_fuel", name: "Packaged Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Fuel.png" },
  packaged_liquid_biofuel: { id: "packaged_liquid_biofuel", name: "Packaged Liquid Biofuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Liquid_Biofuel.png" },
  packaged_turbofuel: { id: "packaged_turbofuel", name: "Packaged Turbofuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Turbofuel.png" },
  packaged_rocket_fuel: { id: "packaged_rocket_fuel", name: "Packaged Rocket Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Rocket_Fuel.png" },
  packaged_ionized_fuel: { id: "packaged_ionized_fuel", name: "Packaged Ionized Fuel", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packaged_Ionized_Fuel.png" },
  uranium_fuel_rod: { id: "uranium_fuel_rod", name: "Uranium Fuel Rod", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Uranium_Fuel_Rod.png" },
  plutonium_fuel_rod: { id: "plutonium_fuel_rod", name: "Plutonium Fuel Rod", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Plutonium_Fuel_Rod.png" },
  black_powder: { id: "black_powder", name: "Black Powder", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Black_Powder.png" },
  smokeless_powder: { id: "smokeless_powder", name: "Smokeless Powder", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Smokeless_Powder.png" },
  gas_filter: { id: "gas_filter", name: "Gas Filter", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Gas_Filter.png" },
  color_cartridge: { id: "color_cartridge", name: "Color Cartridge", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Color_Cartridge.png" },
  beacon: { id: "beacon", name: "Beacon", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Beacon.png" },
  iodine_infused_filter: { id: "iodine_infused_filter", name: "Iodine-Infused Filter", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iodine-Infused_Filter.png" },
  iron_rebar: { id: "iron_rebar", name: "Iron Rebar", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Iron_Rebar.png" },
  stun_rebar: { id: "stun_rebar", name: "Stun Rebar", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Stun_Rebar.png" },
  shatter_rebar: { id: "shatter_rebar", name: "Shatter Rebar", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Shatter_Rebar.png" },
  explosive_rebar: { id: "explosive_rebar", name: "Explosive Rebar", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Explosive_Rebar.png" },
  rifle_ammo: { id: "rifle_ammo", name: "Rifle Ammo", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Rifle_Ammo.png" },
  homing_rifle_ammo: { id: "homing_rifle_ammo", name: "Homing Rifle Ammo", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Homing_Rifle_Ammo.png" },
  turbo_rifle_ammo: { id: "turbo_rifle_ammo", name: "Turbo Rifle Ammo", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Turbo_Rifle_Ammo.png" },
  nobelisk: { id: "nobelisk", name: "Nobelisk", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Nobelisk.png" },
  gas_nobelisk: { id: "gas_nobelisk", name: "Gas Nobelisk", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Gas_Nobelisk.png" },
  pulse_nobelisk: { id: "pulse_nobelisk", name: "Pulse Nobelisk", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Pulse_Nobelisk.png" },
  cluster_nobelisk: { id: "cluster_nobelisk", name: "Cluster Nobelisk", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Cluster_Nobelisk.png" },
  nuke_nobelisk: { id: "nuke_nobelisk", name: "Nuke Nobelisk", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Nuke_Nobelisk.png" },
  electromagnetic_control_rod: { id: "electromagnetic_control_rod", name: "Electromagnetic Control Rod", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Electromagnetic_Control_Rod.png" },
  encased_uranium_cell: { id: "encased_uranium_cell", name: "Encased Uranium Cell", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Encased_Uranium_Cell.png" },
  non_fissile_uranium: { id: "non_fissile_uranium", name: "Non-Fissile Uranium", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Non-Fissile_Uranium.png" },
  plutonium_pellet: { id: "plutonium_pellet", name: "Plutonium Pellet", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Plutonium_Pellet.png" },
  encased_plutonium_cell: { id: "encased_plutonium_cell", name: "Encased Plutonium Cell", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Encased_Plutonium_Cell.png" },
  ficsonium: { id: "ficsonium", name: "Ficsonium", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ficsonium.png" },
  ficsonium_fuel_rod: { id: "ficsonium_fuel_rod", name: "Ficsonium Fuel Rod", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ficsonium_Fuel_Rod.png" },
  uranium_waste: { id: "uranium_waste", name: "Uranium Waste", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Uranium_Waste.png" },
  plutonium_waste: { id: "plutonium_waste", name: "Plutonium Waste", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Plutonium_Waste.png" },
  blue_power_slug: { id: "blue_power_slug", name: "Blue Power Slug", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Blue_Power_Slug.png" },
  yellow_power_slug: { id: "yellow_power_slug", name: "Yellow Power Slug", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Yellow_Power_Slug.png" },
  purple_power_slug: { id: "purple_power_slug", name: "Purple Power Slug", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Purple_Power_Slug.png" },
  power_shard: { id: "power_shard", name: "Power Shard", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Power_Shard.png" },
  ficsit_coupon: { id: "ficsit_coupon", name: "FICSIT Coupon", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/FICSIT_Coupon.png" },
  smart_plating: { id: "smart_plating", name: "Smart Plating", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Smart_Plating.png" },
  versatile_framework: { id: "versatile_framework", name: "Versatile Framework", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Versatile_Framework.png" },
  automated_wiring: { id: "automated_wiring", name: "Automated Wiring", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Automated_Wiring.png" },
  modular_engine: { id: "modular_engine", name: "Modular Engine", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Modular_Engine.png" },
  adaptive_control_unit: { id: "adaptive_control_unit", name: "Adaptive Control Unit", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Adaptive_Control_Unit.png" },
  assembly_director_system: { id: "assembly_director_system", name: "Assembly Director System", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Assembly_Director_System.png" },
  magnetic_field_generator: { id: "magnetic_field_generator", name: "Magnetic Field Generator", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Magnetic_Field_Generator.png" },
  thermal_propulsion_rocket: { id: "thermal_propulsion_rocket", name: "Thermal Propulsion Rocket", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Thermal_Propulsion_Rocket.png" },
  nuclear_pasta: { id: "nuclear_pasta", name: "Nuclear Pasta", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Nuclear_Pasta.png" },
  biochemical_sculptor: { id: "biochemical_sculptor", name: "Biochemical Sculptor", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Biochemical_Sculptor.png" },
  ballistic_warp_drive: { id: "ballistic_warp_drive", name: "Ballistic Warp Drive", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Ballistic_Warp_Drive.png" },
  ai_expansion_server: { id: "ai_expansion_server", name: "AI Expansion Server", imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/AI_Expansion_Server.png" },
};

export type BeltId = string;

export interface Belt {
  id: BeltId;
  name: string;
  capacity: number; // items per minute
}

export const belts: Record<BeltId, Belt> = {
  mk1: { id: "mk1", name: "Mk.1 Belt", capacity: 60 },
  mk2: { id: "mk2", name: "Mk.2 Belt", capacity: 120 },
  mk3: { id: "mk3", name: "Mk.3 Belt", capacity: 270 },
  mk4: { id: "mk4", name: "Mk.4 Belt", capacity: 480 },
  mk5: { id: "mk5", name: "Mk.5 Belt", capacity: 780 },
};

export const machines: Record<MachineId, Machine> = {
  miner_mk1: { id: "miner_mk1", name: "Miner Mk.1", powerUsage: 5, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Miner_Mk1.png" },
  miner_mk2: { id: "miner_mk2", name: "Miner Mk.2", powerUsage: 12, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Miner_Mk2.png" },
  miner_mk3: { id: "miner_mk3", name: "Miner Mk.3", powerUsage: 30, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Miner_Mk3.png" },
  water_extractor: { id: "water_extractor", name: "Water Extractor", powerUsage: 20, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Water_Extractor.png" },
  oil_extractor: { id: "oil_extractor", name: "Oil Extractor", powerUsage: 40, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Oil_Extractor.png" },
  resource_well_pressurizer: { id: "resource_well_pressurizer", name: "Resource Well Pressurizer", powerUsage: 150, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Resource_Well_Pressurizer.png" },
  smelter: { id: "smelter", name: "Smelter", powerUsage: 4, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Smelter.png" },
  foundry: { id: "foundry", name: "Foundry", powerUsage: 16, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Foundry.png" },
  constructor: { id: "constructor", name: "Constructor", powerUsage: 4, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Constructor.png" },
  assembler: { id: "assembler", name: "Assembler", powerUsage: 15, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Assembler.png" },
  manufacturer: { id: "manufacturer", name: "Manufacturer", powerUsage: 55, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Manufacturer.png" },
  refinery: { id: "refinery", name: "Refinery", powerUsage: 30, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Refinery.png" },
  blender: { id: "blender", name: "Blender", powerUsage: 75, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Blender.png" },
  packager: { id: "packager", name: "Packager", powerUsage: 10, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Packager.png" },
  particle_accelerator: { id: "particle_accelerator", name: "Particle Accelerator", powerUsage: 250, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Particle_Accelerator.png" },
  quantum_encoder: { id: "quantum_encoder", name: "Quantum Encoder", powerUsage: 1000, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Quantum_Encoder.png" },
  converter: { id: "converter", name: "Converter", powerUsage: 250, imageUrl: "https://satisfactory.wiki.gg/wiki/Special:FilePath/Converter.png" },
};

export const recipes: Recipe[] = [
  {
    id: "recipe_copper_ore",
    outputItemId: "copper_ore",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_iron_ore",
    outputItemId: "iron_ore",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_limestone",
    outputItemId: "limestone",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_coal",
    outputItemId: "coal",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_caterium_ore",
    outputItemId: "caterium_ore",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_raw_quartz",
    outputItemId: "raw_quartz",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_sulfur",
    outputItemId: "sulfur",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_bauxite",
    outputItemId: "bauxite",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_sam",
    outputItemId: "sam",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_uranium",
    outputItemId: "uranium",
    outputRate: 60,
    inputs: [],
    machineId: "miner_mk1",
  },
  {
    id: "recipe_water",
    outputItemId: "water",
    outputRate: 120,
    inputs: [],
    machineId: "water_extractor",
  },
  {
    id: "recipe_crude_oil",
    outputItemId: "crude_oil",
    outputRate: 120,
    inputs: [],
    machineId: "oil_extractor",
  },
  {
    id: "recipe_nitrogen_gas",
    outputItemId: "nitrogen_gas",
    outputRate: 120,
    inputs: [],
    machineId: "resource_well_pressurizer",
  },
  {
    id: "recipe_copper_ingot",
    outputItemId: "copper_ingot",
    outputRate: 30,
    inputs: [{ itemId: "copper_ore", rate: 30 }],
    machineId: "smelter",
  },
  {
    id: "recipe_iron_ingot",
    outputItemId: "iron_ingot",
    outputRate: 30,
    inputs: [{ itemId: "iron_ore", rate: 30 }],
    machineId: "smelter",
  },
  {
    id: "recipe_caterium_ingot",
    outputItemId: "caterium_ingot",
    outputRate: 15,
    inputs: [{ itemId: "caterium_ore", rate: 45 }],
    machineId: "smelter",
  },
  {
    id: "recipe_steel_ingot",
    outputItemId: "steel_ingot",
    outputRate: 45,
    inputs: [{ itemId: "iron_ore", rate: 45 }, { itemId: "coal", rate: 45 }],
    machineId: "foundry",
  },
  {
    id: "recipe_aluminum_ingot",
    outputItemId: "aluminum_ingot",
    outputRate: 60,
    inputs: [{ itemId: "aluminum_scrap", rate: 90 }, { itemId: "silica", rate: 75 }],
    machineId: "foundry",
  },
  {
    id: "recipe_ficsite_ingot",
    outputItemId: "ficsite_ingot",
    outputRate: 30,
    inputs: [{ itemId: "iron_ore", rate: 30 }, { itemId: "sam", rate: 30 }],
    machineId: "smelter",
  },
  {
    id: "recipe_iron_plate",
    outputItemId: "iron_plate",
    outputRate: 20,
    inputs: [{ itemId: "iron_ingot", rate: 30 }],
    machineId: "constructor",
  },
  {
    id: "recipe_iron_rod",
    outputItemId: "iron_rod",
    outputRate: 15,
    inputs: [{ itemId: "iron_ingot", rate: 15 }],
    machineId: "constructor",
  },
  {
    id: "recipe_screw",
    outputItemId: "screw",
    outputRate: 40,
    inputs: [{ itemId: "iron_rod", rate: 10 }],
    machineId: "constructor",
  },
  {
    id: "recipe_wire",
    outputItemId: "wire",
    outputRate: 30,
    inputs: [{ itemId: "copper_ingot", rate: 15 }],
    machineId: "constructor",
  },
  {
    id: "recipe_cable",
    outputItemId: "cable",
    outputRate: 30,
    inputs: [{ itemId: "wire", rate: 60 }],
    machineId: "constructor",
  },
  {
    id: "recipe_copper_sheet",
    outputItemId: "copper_sheet",
    outputRate: 10,
    inputs: [{ itemId: "copper_ingot", rate: 20 }],
    machineId: "constructor",
  },
  {
    id: "recipe_concrete",
    outputItemId: "concrete",
    outputRate: 15,
    inputs: [{ itemId: "limestone", rate: 45 }],
    machineId: "constructor",
  },
  {
    id: "recipe_reinforced_iron_plate",
    outputItemId: "reinforced_iron_plate",
    outputRate: 5,
    inputs: [{ itemId: "iron_plate", rate: 30 }, { itemId: "screw", rate: 60 }],
    machineId: "assembler",
  },
  {
    id: "recipe_rotor",
    outputItemId: "rotor",
    outputRate: 4,
    inputs: [{ itemId: "iron_rod", rate: 20 }, { itemId: "screw", rate: 100 }],
    machineId: "assembler",
  },
  {
    id: "recipe_biomass_leaves",
    outputItemId: "biomass",
    outputRate: 60,
    inputs: [{ itemId: "leaves", rate: 120 }],
    machineId: "constructor",
  },
  {
    id: "recipe_biomass_wood",
    outputItemId: "biomass",
    outputRate: 300,
    inputs: [{ itemId: "wood", rate: 37.5 }],
    machineId: "constructor",
  },
  {
    id: "recipe_solid_biofuel",
    outputItemId: "solid_biofuel",
    outputRate: 60,
    inputs: [{ itemId: "biomass", rate: 120 }],
    machineId: "constructor",
  },
  {
    id: "recipe_steel_beam",
    outputItemId: "steel_beam",
    outputRate: 15,
    inputs: [{ itemId: "steel_ingot", rate: 60 }],
    machineId: "constructor",
  },
  {
    id: "recipe_steel_pipe",
    outputItemId: "steel_pipe",
    outputRate: 20,
    inputs: [{ itemId: "steel_ingot", rate: 30 }],
    machineId: "constructor",
  },
  {
    id: "recipe_encased_industrial_beam",
    outputItemId: "encased_industrial_beam",
    outputRate: 6,
    inputs: [{ itemId: "steel_beam", rate: 18 }, { itemId: "concrete", rate: 36 }],
    machineId: "assembler",
  },
  {
    id: "recipe_stator",
    outputItemId: "stator",
    outputRate: 5,
    inputs: [{ itemId: "steel_pipe", rate: 15 }, { itemId: "wire", rate: 40 }],
    machineId: "assembler",
  },
  {
    id: "recipe_motor",
    outputItemId: "motor",
    outputRate: 5,
    inputs: [{ itemId: "rotor", rate: 10 }, { itemId: "stator", rate: 10 }],
    machineId: "assembler",
  },
  {
    id: "recipe_modular_frame",
    outputItemId: "modular_frame",
    outputRate: 2,
    inputs: [{ itemId: "reinforced_iron_plate", rate: 3 }, { itemId: "iron_rod", rate: 12 }],
    machineId: "assembler",
  },
  {
    id: "recipe_heavy_modular_frame",
    outputItemId: "heavy_modular_frame",
    outputRate: 2,
    inputs: [{ itemId: "modular_frame", rate: 10 }, { itemId: "steel_pipe", rate: 30 }, { itemId: "encased_industrial_beam", rate: 10 }, { itemId: "screw", rate: 200 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_quickwire",
    outputItemId: "quickwire",
    outputRate: 60,
    inputs: [{ itemId: "caterium_ingot", rate: 12 }],
    machineId: "constructor",
  },
  {
    id: "recipe_silica",
    outputItemId: "silica",
    outputRate: 37.5,
    inputs: [{ itemId: "raw_quartz", rate: 22.5 }],
    machineId: "constructor",
  },
  {
    id: "recipe_quartz_crystal",
    outputItemId: "quartz_crystal",
    outputRate: 22.5,
    inputs: [{ itemId: "raw_quartz", rate: 37.5 }],
    machineId: "constructor",
  },
  {
    id: "recipe_plastic",
    outputItemId: "plastic",
    outputRate: 20,
    inputs: [{ itemId: "crude_oil", rate: 30 }],
    machineId: "refinery",
  },
  {
    id: "recipe_rubber",
    outputItemId: "rubber",
    outputRate: 20,
    inputs: [{ itemId: "crude_oil", rate: 30 }],
    machineId: "refinery",
  },
  {
    id: "recipe_heavy_oil_residue",
    outputItemId: "heavy_oil_residue",
    outputRate: 40,
    inputs: [{ itemId: "crude_oil", rate: 30 }],
    machineId: "refinery",
  },
  {
    id: "recipe_petroleum_coke",
    outputItemId: "petroleum_coke",
    outputRate: 120,
    inputs: [{ itemId: "heavy_oil_residue", rate: 40 }],
    machineId: "refinery",
  },
  {
    id: "recipe_fuel",
    outputItemId: "fuel",
    outputRate: 40,
    inputs: [{ itemId: "crude_oil", rate: 60 }],
    machineId: "refinery",
  },
  {
    id: "recipe_circuit_board",
    outputItemId: "circuit_board",
    outputRate: 7.5,
    inputs: [{ itemId: "copper_sheet", rate: 15 }, { itemId: "plastic", rate: 30 }],
    machineId: "assembler",
  },
  {
    id: "recipe_computer",
    outputItemId: "computer",
    outputRate: 2.5,
    inputs: [{ itemId: "circuit_board", rate: 25 }, { itemId: "cable", rate: 22.5 }, { itemId: "plastic", rate: 45 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_ai_limiter",
    outputItemId: "ai_limiter",
    outputRate: 5,
    inputs: [{ itemId: "copper_sheet", rate: 25 }, { itemId: "quickwire", rate: 100 }],
    machineId: "assembler",
  },
  {
    id: "recipe_high_speed_connector",
    outputItemId: "high_speed_connector",
    outputRate: 3.75,
    inputs: [{ itemId: "quickwire", rate: 210 }, { itemId: "cable", rate: 37.5 }, { itemId: "circuit_board", rate: 3.75 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_alumina_solution",
    outputItemId: "alumina_solution",
    outputRate: 120,
    inputs: [{ itemId: "bauxite", rate: 120 }, { itemId: "water", rate: 180 }],
    machineId: "refinery",
  },
  {
    id: "recipe_aluminum_scrap",
    outputItemId: "aluminum_scrap",
    outputRate: 360,
    inputs: [{ itemId: "alumina_solution", rate: 240 }, { itemId: "coal", rate: 120 }],
    machineId: "refinery",
  },
  {
    id: "recipe_aluminum_casing",
    outputItemId: "aluminum_casing",
    outputRate: 60,
    inputs: [{ itemId: "aluminum_ingot", rate: 90 }],
    machineId: "constructor",
  },
  {
    id: "recipe_alclad_aluminum_sheet",
    outputItemId: "alclad_aluminum_sheet",
    outputRate: 30,
    inputs: [{ itemId: "aluminum_ingot", rate: 30 }, { itemId: "copper_ingot", rate: 10 }],
    machineId: "assembler",
  },
  {
    id: "recipe_battery",
    outputItemId: "battery",
    outputRate: 20,
    inputs: [{ itemId: "sulfuric_acid", rate: 50 }, { itemId: "alumina_solution", rate: 40 }, { itemId: "aluminum_casing", rate: 20 }],
    machineId: "blender",
  },
  {
    id: "recipe_radio_control_unit",
    outputItemId: "radio_control_unit",
    outputRate: 2.5,
    inputs: [{ itemId: "aluminum_casing", rate: 80 }, { itemId: "crystal_oscillator", rate: 1.25 }, { itemId: "computer", rate: 1.25 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_sulfuric_acid",
    outputItemId: "sulfuric_acid",
    outputRate: 50,
    inputs: [{ itemId: "sulfur", rate: 50 }, { itemId: "water", rate: 50 }],
    machineId: "refinery",
  },
  {
    id: "recipe_nitric_acid",
    outputItemId: "nitric_acid",
    outputRate: 30,
    inputs: [{ itemId: "nitrogen_gas", rate: 120 }, { itemId: "water", rate: 30 }, { itemId: "iron_plate", rate: 10 }],
    machineId: "blender",
  },
  {
    id: "recipe_copper_powder",
    outputItemId: "copper_powder",
    outputRate: 50,
    inputs: [{ itemId: "copper_ingot", rate: 300 }],
    machineId: "constructor",
  },
  {
    id: "recipe_crystal_oscillator",
    outputItemId: "crystal_oscillator",
    outputRate: 1,
    inputs: [{ itemId: "quartz_crystal", rate: 18 }, { itemId: "cable", rate: 14 }, { itemId: "reinforced_iron_plate", rate: 2.5 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_cooling_system",
    outputItemId: "cooling_system",
    outputRate: 6,
    inputs: [{ itemId: "heat_sink", rate: 12 }, { itemId: "rubber", rate: 12 }, { itemId: "water", rate: 30 }, { itemId: "nitrogen_gas", rate: 150 }],
    machineId: "blender",
  },
  {
    id: "recipe_heat_sink",
    outputItemId: "heat_sink",
    outputRate: 7.5,
    inputs: [{ itemId: "alclad_aluminum_sheet", rate: 37.5 }, { itemId: "copper_sheet", rate: 22.5 }],
    machineId: "assembler",
  },
  {
    id: "recipe_fused_modular_frame",
    outputItemId: "fused_modular_frame",
    outputRate: 1.5,
    inputs: [{ itemId: "heavy_modular_frame", rate: 1.5 }, { itemId: "aluminum_casing", rate: 75 }, { itemId: "nitrogen_gas", rate: 37.5 }],
    machineId: "blender",
  },
  {
    id: "recipe_turbo_motor",
    outputItemId: "turbo_motor",
    outputRate: 1.875,
    inputs: [{ itemId: "cooling_system", rate: 7.5 }, { itemId: "radio_control_unit", rate: 3.75 }, { itemId: "motor", rate: 7.5 }, { itemId: "rubber", rate: 45 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_supercomputer",
    outputItemId: "supercomputer",
    outputRate: 1.875,
    inputs: [{ itemId: "computer", rate: 3.75 }, { itemId: "ai_limiter", rate: 3.75 }, { itemId: "high_speed_connector", rate: 5.625 }, { itemId: "plastic", rate: 52.5 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_electromagnetic_control_rod",
    outputItemId: "electromagnetic_control_rod",
    outputRate: 4,
    inputs: [{ itemId: "stator", rate: 6 }, { itemId: "ai_limiter", rate: 4 }],
    machineId: "assembler",
  },
  {
    id: "recipe_smart_plating",
    outputItemId: "smart_plating",
    outputRate: 2,
    inputs: [{ itemId: "reinforced_iron_plate", rate: 2 }, { itemId: "rotor", rate: 2 }],
    machineId: "assembler",
  },
  {
    id: "recipe_versatile_framework",
    outputItemId: "versatile_framework",
    outputRate: 5,
    inputs: [{ itemId: "modular_frame", rate: 2.5 }, { itemId: "steel_beam", rate: 30 }],
    machineId: "assembler",
  },
  {
    id: "recipe_automated_wiring",
    outputItemId: "automated_wiring",
    outputRate: 2.5,
    inputs: [{ itemId: "stator", rate: 2.5 }, { itemId: "cable", rate: 50 }],
    machineId: "assembler",
  },
  {
    id: "recipe_modular_engine",
    outputItemId: "modular_engine",
    outputRate: 1,
    inputs: [{ itemId: "motor", rate: 2 }, { itemId: "rubber", rate: 15 }, { itemId: "smart_plating", rate: 2 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_adaptive_control_unit",
    outputItemId: "adaptive_control_unit",
    outputRate: 1,
    inputs: [{ itemId: "automated_wiring", rate: 7.5 }, { itemId: "circuit_board", rate: 5 }, { itemId: "heavy_modular_frame", rate: 1 }, { itemId: "computer", rate: 1 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_assembly_director_system",
    outputItemId: "assembly_director_system",
    outputRate: 0.75,
    inputs: [{ itemId: "adaptive_control_unit", rate: 1.5 }, { itemId: "supercomputer", rate: 0.75 }],
    machineId: "assembler",
  },
  {
    id: "recipe_magnetic_field_generator",
    outputItemId: "magnetic_field_generator",
    outputRate: 1,
    inputs: [{ itemId: "versatile_framework", rate: 2.5 }, { itemId: "electromagnetic_control_rod", rate: 1 }],
    machineId: "assembler",
  },
  {
    id: "recipe_thermal_propulsion_rocket",
    outputItemId: "thermal_propulsion_rocket",
    outputRate: 0.5,
    inputs: [{ itemId: "modular_engine", rate: 2.5 }, { itemId: "turbo_motor", rate: 0.5 }, { itemId: "cooling_system", rate: 1.5 }, { itemId: "fused_modular_frame", rate: 0.5 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_nuclear_pasta",
    outputItemId: "nuclear_pasta",
    outputRate: 0.5,
    inputs: [{ itemId: "copper_powder", rate: 100 }, { itemId: "pressure_conversion_cube", rate: 0.5 }],
    machineId: "particle_accelerator",
  },
  {
    id: "recipe_alien_protein",
    outputItemId: "alien_protein",
    outputRate: 20,
    inputs: [{ itemId: "alien_dna_capsule", rate: 10 }],
    machineId: "constructor",
  },
  {
    id: "recipe_alien_dna_capsule",
    outputItemId: "alien_dna_capsule",
    outputRate: 10,
    inputs: [{ itemId: "alien_protein", rate: 10 }],
    machineId: "constructor",
  },
  {
    id: "recipe_reanimated_sam",
    outputItemId: "reanimated_sam",
    outputRate: 30,
    inputs: [{ itemId: "sam", rate: 120 }],
    machineId: "constructor",
  },
  {
    id: "recipe_sam_fluctuator",
    outputItemId: "sam_fluctuator",
    outputRate: 10,
    inputs: [{ itemId: "reanimated_sam", rate: 30 }, { itemId: "wire", rate: 50 }],
    machineId: "assembler",
  },
  {
    id: "recipe_superposition_oscillator",
    outputItemId: "superposition_oscillator",
    outputRate: 1,
    inputs: [{ itemId: "crystal_oscillator", rate: 1 }, { itemId: "sam_fluctuator", rate: 1 }],
    machineId: "assembler",
  },
  {
    id: "recipe_diamonds",
    outputItemId: "diamonds",
    outputRate: 10,
    inputs: [{ itemId: "coal", rate: 100 }],
    machineId: "particle_accelerator",
  },
  {
    id: "recipe_time_crystal",
    outputItemId: "time_crystal",
    outputRate: 5,
    inputs: [{ itemId: "diamonds", rate: 10 }, { itemId: "reanimated_sam", rate: 10 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_dark_matter_crystal",
    outputItemId: "dark_matter_crystal",
    outputRate: 5,
    inputs: [{ itemId: "diamonds", rate: 5 }, { itemId: "dark_matter_residue", rate: 50 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_singularity_cell",
    outputItemId: "singularity_cell",
    outputRate: 1,
    inputs: [{ itemId: "nuclear_pasta", rate: 1 }, { itemId: "dark_matter_crystal", rate: 10 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_neural_quantum_processor",
    outputItemId: "neural_quantum_processor",
    outputRate: 1,
    inputs: [{ itemId: "supercomputer", rate: 1 }, { itemId: "superposition_oscillator", rate: 1 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_alien_power_matrix",
    outputItemId: "alien_power_matrix",
    outputRate: 1,
    inputs: [{ itemId: "singularity_cell", rate: 1 }, { itemId: "sam_fluctuator", rate: 10 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_ficsite_trigon",
    outputItemId: "ficsite_trigon",
    outputRate: 10,
    inputs: [{ itemId: "ficsite_ingot", rate: 10 }],
    machineId: "constructor",
  },
  {
    id: "recipe_biochemical_sculptor",
    outputItemId: "biochemical_sculptor",
    outputRate: 1,
    inputs: [{ itemId: "alien_power_matrix", rate: 1 }, { itemId: "ficsite_trigon", rate: 10 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_ballistic_warp_drive",
    outputItemId: "ballistic_warp_drive",
    outputRate: 1,
    inputs: [{ itemId: "thermal_propulsion_rocket", rate: 1 }, { itemId: "singularity_cell", rate: 1 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_ai_expansion_server",
    outputItemId: "ai_expansion_server",
    outputRate: 1,
    inputs: [{ itemId: "neural_quantum_processor", rate: 1 }, { itemId: "assembly_director_system", rate: 1 }],
    machineId: "quantum_encoder",
  },
  {
    id: "recipe_excited_photonic_matter",
    outputItemId: "excited_photonic_matter",
    outputRate: 50,
    inputs: [{ itemId: "sam", rate: 50 }],
    machineId: "converter",
  },
  {
    id: "recipe_dark_matter_residue",
    outputItemId: "dark_matter_residue",
    outputRate: 50,
    inputs: [{ itemId: "excited_photonic_matter", rate: 50 }],
    machineId: "converter",
  },
  {
    id: "recipe_encased_uranium_cell",
    outputItemId: "encased_uranium_cell",
    outputRate: 20,
    inputs: [{ itemId: "uranium", rate: 40 }, { itemId: "concrete", rate: 15 }, { itemId: "sulfuric_acid", rate: 40 }],
    machineId: "blender",
  },
  {
    id: "recipe_uranium_fuel_rod",
    outputItemId: "uranium_fuel_rod",
    outputRate: 0.4,
    inputs: [{ itemId: "encased_uranium_cell", rate: 20 }, { itemId: "encased_industrial_beam", rate: 1.2 }, { itemId: "electromagnetic_control_rod", rate: 2 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_non_fissile_uranium",
    outputItemId: "non_fissile_uranium",
    outputRate: 50,
    inputs: [{ itemId: "uranium_waste", rate: 37.5 }, { itemId: "silica", rate: 25 }, { itemId: "nitric_acid", rate: 15 }, { itemId: "sulfuric_acid", rate: 15 }],
    machineId: "blender",
  },
  {
    id: "recipe_plutonium_pellet",
    outputItemId: "plutonium_pellet",
    outputRate: 30,
    inputs: [{ itemId: "non_fissile_uranium", rate: 100 }, { itemId: "uranium_waste", rate: 25 }],
    machineId: "particle_accelerator",
  },
  {
    id: "recipe_encased_plutonium_cell",
    outputItemId: "encased_plutonium_cell",
    outputRate: 10,
    inputs: [{ itemId: "plutonium_pellet", rate: 20 }, { itemId: "concrete", rate: 40 }],
    machineId: "assembler",
  },
  {
    id: "recipe_plutonium_fuel_rod",
    outputItemId: "plutonium_fuel_rod",
    outputRate: 0.25,
    inputs: [{ itemId: "encased_plutonium_cell", rate: 7.5 }, { itemId: "steel_beam", rate: 4.5 }, { itemId: "electromagnetic_control_rod", rate: 1.5 }, { itemId: "heat_sink", rate: 2.5 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_ficsonium",
    outputItemId: "ficsonium",
    outputRate: 10,
    inputs: [{ itemId: "plutonium_waste", rate: 10 }, { itemId: "dark_matter_residue", rate: 10 }],
    machineId: "particle_accelerator",
  },
  {
    id: "recipe_ficsonium_fuel_rod",
    outputItemId: "ficsonium_fuel_rod",
    outputRate: 1,
    inputs: [{ itemId: "ficsonium", rate: 10 }, { itemId: "electromagnetic_control_rod", rate: 1 }],
    machineId: "manufacturer",
  },
  {
    id: "recipe_empty_canister",
    outputItemId: "empty_canister",
    outputRate: 60,
    inputs: [{ itemId: "plastic", rate: 30 }],
    machineId: "constructor",
  },
  {
    id: "recipe_packaged_water",
    outputItemId: "packaged_water",
    outputRate: 60,
    inputs: [{ itemId: "water", rate: 60 }, { itemId: "empty_canister", rate: 60 }],
    machineId: "packager",
  },
  {
    id: "recipe_turbofuel",
    outputItemId: "turbofuel",
    outputRate: 18.75,
    inputs: [{ itemId: "fuel", rate: 22.5 }, { itemId: "compacted_coal", rate: 15 }],
    machineId: "refinery",
  },
  {
    id: "recipe_compacted_coal",
    outputItemId: "compacted_coal",
    outputRate: 25,
    inputs: [{ itemId: "coal", rate: 25 }, { itemId: "sulfur", rate: 25 }],
    machineId: "assembler",
  },
  {
    id: "recipe_rocket_fuel",
    outputItemId: "rocket_fuel",
    outputRate: 50,
    inputs: [{ itemId: "turbofuel", rate: 50 }, { itemId: "nitric_acid", rate: 10 }],
    machineId: "blender",
  },
  {
    id: "recipe_ionized_fuel",
    outputItemId: "ionized_fuel",
    outputRate: 40,
    inputs: [{ itemId: "rocket_fuel", rate: 40 }, { itemId: "power_shard", rate: 1 }],
    machineId: "blender",
  },
  {
    id: "recipe_black_powder",
    outputItemId: "black_powder",
    outputRate: 30,
    inputs: [{ itemId: "coal", rate: 15 }, { itemId: "sulfur", rate: 15 }],
    machineId: "assembler",
  },
  {
    id: "recipe_smokeless_powder",
    outputItemId: "smokeless_powder",
    outputRate: 20,
    inputs: [{ itemId: "black_powder", rate: 20 }, { itemId: "heavy_oil_residue", rate: 10 }],
    machineId: "refinery",
  },
  {
    id: "recipe_nobelisk",
    outputItemId: "nobelisk",
    outputRate: 3,
    inputs: [{ itemId: "black_powder", rate: 15 }, { itemId: "steel_pipe", rate: 15 }],
    machineId: "assembler",
  },
  {
    id: "recipe_iron_rebar",
    outputItemId: "iron_rebar",
    outputRate: 15,
    inputs: [{ itemId: "iron_rod", rate: 15 }],
    machineId: "constructor",
  },
  {
    id: "recipe_rifle_ammo",
    outputItemId: "rifle_ammo",
    outputRate: 75,
    inputs: [{ itemId: "copper_sheet", rate: 15 }, { itemId: "smokeless_powder", rate: 10 }],
    machineId: "assembler",
  },
  {
    id: "recipe_pressure_conversion_cube",
    outputItemId: "pressure_conversion_cube",
    outputRate: 1,
    inputs: [{ itemId: "fused_modular_frame", rate: 1 }, { itemId: "radio_control_unit", rate: 2 }],
    machineId: "assembler",
  },
];
